### ISSUE TITLE
Issues importing Malaya

### ISSUE THREAD

**Issue by alepnabil** [huseinzol05/malaya#102]
Assalamualaikum,
saya cuba untuk import Malaya tapi ada Importerror yang keluar:

ImportError: cannot import name 'nx' from 'networkx'

Saya sudah cuba uninstall Networkx dan install balik,tetapi masalah ini masih berlaku. Ada cadangan untuk menyelesaikan masalah ini?

Terima kasih.

**Comment by huseinzol05** [comment]
networkx recently released 2.6.2, install networkx <= 2.5.1 should solved the problem.
