### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by chanwwei** [huseinzol05/malaya#103]
Hi Mr Husein, I encountered this error when trying to run the exact codes on my own jupyter notebook, could you please advise? Thank you.

![image](https://user-images.githubusercontent.com/82443116/132943133-51aded39-5bd3-4410-9574-1a4fb91b2390.png)

**Comment by huseinzol05** [comment]
Which malaya version is this? seems like an old version, make sure latest version,

```bash
pip install malaya -U
```

**Comment by chanwwei** [comment]
![image](https://user-images.githubusercontent.com/82443116/132955432-028d3a6a-49d7-4dd0-ad08-ff265be411d5.png)
![image](https://user-images.githubusercontent.com/82443116/132955460-0dd1f7bc-89d2-482f-9236-1fbcc330435b.png)

Hi Mr Husein, I did the steps, but still hitting the same error

**Comment by huseinzol05** [comment]
Tested in colab, no problem, https://colab.research.google.com/drive/1gCIZyLXapB59rC0nVtPZ9Dufzui3snom?usp=sharing

Maybe can try,

```bash
malaya.utils.delete_cache('preprocessing')
```

And rerun the code again, your caching might corrupt.

**Comment by chanwwei** [comment]
Mr Husein, thanks for advise, it solved the problem. However, I have another issue in running the tokenizer. I have tried to run on the google colab, hitting the same error. 

![image](https://user-images.githubusercontent.com/82443116/132973017-dba29323-703c-44d9-a155-4b5e8d57e4a9.png)

**Comment by chanwwei** [comment]
Mr Husein, may I know how can I apply the preprocessing function on dataframe? 
I have attached my codes here: https://colab.research.google.com/drive/17mwZEj72-FyzVxYE8kc4zgGD2E-QRzYB?usp=sharing

![image](https://user-images.githubusercontent.com/82443116/133411545-f3248508-84f8-4d64-8d23-4af928eb4f68.png)
