### ISSUE TITLE
Using preprocess functions on dataframe

### ISSUE THREAD

**Issue by chanwwei** [huseinzol05/malaya#104]
Mr Husein, may I know how can I apply the preprocessing function on dataframe? 
I have attached my codes here: https://colab.research.google.com/drive/17mwZEj72-FyzVxYE8kc4zgGD2E-QRzYB?usp=sharing

![image](https://user-images.githubusercontent.com/82443116/133452875-e2cd7920-9f15-4679-a0e0-9607fce915e5.png)

**Comment by huseinzol05** [comment]
Not an actual issue related to the repo.
