### ISSUE TITLE
GPU issue on Encoder Transformer Electra spelling correction model

### ISSUE THREAD

**Issue by FathiKR** [huseinzol05/malaya#109]
I tried to run the encoder transformer model (Electra) on several texts data (1000 total) by using google colab (GPU) . But after reaching 35th rows, it said the environment RAM has been used up. So here is the 35th index that was requested.

`text_index35 = 'kan bagus servis mcm ni boleh bt utk tukar suami baru suami aku tu jenis kedekut dah lah pinjam duit aku tak nk byr harap aku bg hantaran murah dah dulu tp tak hargai dah lah nk tukar suami baru maybe boleh dpt yg lebih elok utk tahan lama kali ni'`

Reference
![image](https://user-images.githubusercontent.com/79899914/144420703-06dc2bef-4229-42a1-831e-b359d0126303.png)

**Comment by huseinzol05** [comment]
Thanks! will look into it asap.
