### ISSUE TITLE
Problems when downloading transformer model

### ISSUE THREAD

**Issue by nadiahazib** [huseinzol05/malaya#111]
I’ve installed the Malaya library and tensorflow using Jupyter notebook, and tested out the tokenizer, corrector and normalizer functions on some strings; they work just fine. However, I ran into some problems when trying to download a model to run POS-tagging, please advise, thank you.

EXAMPLE

in:
--------------------------------------------------------------------------
model = malaya.pos.transformer(model = 'tiny-albert')
-------------------------------------------------------------------------

out:
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\anaconda3\lib\site-packages\google\protobuf\internal\python_message.py in MergeFromString(self, serialized)
   1138     try:
-> 1139       if self._InternalParse(serialized, 0, length) != length:
   1140         # The only reason _InternalParse would return early is if it
 
~\anaconda3\lib\site-packages\google\protobuf\internal\python_message.py in InternalParse(self, buffer, pos, end)
   1191         old_pos = new_pos
-> 1192         (data, new_pos) = decoder._DecodeUnknownField(
   1193             buffer, new_pos, wire_type)  # pylint: disable=protected-access
 
~\anaconda3\lib\site-packages\google\protobuf\internal\decoder.py in _DecodeUnknownField(buffer, pos, wire_type)
    988   elif wire_type == wire_format.WIRETYPE_START_GROUP:
--> 989     (data, pos) = _DecodeUnknownFieldSet(buffer, pos)
    990   elif wire_type == wire_format.WIRETYPE_END_GROUP:
 
~\anaconda3\lib\site-packages\google\protobuf\internal\decoder.py in _DecodeUnknownFieldSet(buffer, pos, end_pos)
    962   while end_pos is None or pos < end_pos:
--> 963     (tag_bytes, pos) = ReadTag(buffer, pos)
    964     (tag, _) = _DecodeVarint(tag_bytes, 0)
 
~\anaconda3\lib\site-packages\google\protobuf\internal\decoder.py in ReadTag(buffer, pos)
    191   start = pos
--> 192   while six.indexbytes(buffer, pos) & 0x80:
    193     pos += 1
 
IndexError: index out of bounds on dimension 1
 
During handling of the above exception, another exception occurred:
 
DecodeError                               Traceback (most recent call last)
~\anaconda3\lib\site-packages\malaya\function\__init__.py in load_graph(frozen_graph_filename, **kwargs)
    144             graph_def = tf.compat.v1.GraphDef()
--> 145             graph_def.ParseFromString(f.read())
    146         except Exception as e:
 
~\anaconda3\lib\site-packages\google\protobuf\message.py in ParseFromString(self, serialized)
    198     self.Clear()
--> 199     return self.MergeFromString(serialized)
    200 
 
~\anaconda3\lib\site-packages\google\protobuf\internal\python_message.py in MergeFromString(self, serialized)
   1144       # Now ord(buf[p:p+1]) == ord('') gets TypeError.
-> 1145       raise message_mod.DecodeError('Truncated message.')
   1146     except struct.error as e:
 
DecodeError: Truncated message.
 
During handling of the above exception, another exception occurred:
 
IndexError                                Traceback (most recent call last)
<ipython-input-22-da31b5298671> in <module>
----> 1 model = malaya.pos.transformer(model = 'tiny-albert')
 
~\anaconda3\lib\site-packages\herpetologist\__init__.py in check(*args, **kwargs)
     98                 nested_check(v, p)
     99 
--> 100         return func(*args, **kwargs)
    101 
    102     return check
 
~\anaconda3\lib\site-packages\malaya\pos.py in transformer(model, quantized, **kwargs)
    184             'model not supported, please check supported models from `malaya.pos.available_transformer()`.'
    185         )
--> 186     return tag.transformer(
    187         class_name = 'pos', model = model, quantized = quantized, **kwargs
    188     )
 
~\anaconda3\lib\site-packages\malaya\supervised\tag.py in transformer(class_name, model, quantized, **kwargs)
     31         **kwargs,
     32     )
---> 33     g = load_graph(path['model'], **kwargs)
     34 
     35     try:
 
~\anaconda3\lib\site-packages\malaya\function\__init__.py in load_graph(frozen_graph_filename, **kwargs)
    145             graph_def.ParseFromString(f.read())
    146         except Exception as e:
--> 147             path = frozen_graph_filename.split('Malaya/')[1]
    148             path = '/'.join(path.split('/')[:-1])
    149             raise Exception(
 
IndexError: list index out of range

--------------------------------------------------------------------------

**Comment by huseinzol05** [comment]
seems like old version of malaya version, can you install latest version Malaya?

I tried on google colab, seems like no problem, https://colab.research.google.com/drive/1K8pQRWiCr-oiFzH2qV0-AfaHQr7fH1YG?usp=sharing

**Comment by nadiahazib** [comment]
Hi ,

I’ve just re-installed the get the latest version:



But this error comes up when loading the model:
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 96: character maps to <undefined>




Please advise. Thank you

Salam,
Nadiah

Sent from Mail for Windows

**Comment by huseinzol05** [comment]
Windows issue, https://malaya.readthedocs.io/en/latest/running-on-windows.html#UnicodeDecodeError:-'charmap'-codec-can't-decode-byte

**Comment by nadiahazib** [comment]
Salam,

Issue resolved! POS tagger working. 

Thank you very much!

Nadiah

Sent from Mail for Windows
