### ISSUE TITLE
keyword extraction using transformer

### ISSUE THREAD

**Issue by akmalcm** [huseinzol05/malaya#117]
Cuba untuk guna keyword extraction using transformer bert model. Tapi dapat error ni.

![image](https://user-images.githubusercontent.com/49616983/168531507-3ae4cfff-0acd-485c-9ec4-0d697e299ab5.png)

Python 3.9
TF 2.8.0

**Comment by huseinzol05** [comment]
https://malaya.readthedocs.io/en/latest/running-on-windows.html
