### ISSUE TITLE
cant download file BERT.wordpiece

### ISSUE THREAD

**Issue by serenaroseaini** [huseinzol05/malaya#120]
hi en.Husein,

i cant download one of the file for BERT-bahasa. Error as shown;

https://raw.githubusercontent.com/huseinzol05/Malaya/master/pretrained-model/bert/BERT.wordpiece

HTTPError: HTTP Error 404: Not Found

**Comment by huseinzol05** [comment]
Where do you get this url?

**Comment by serenaroseaini** [comment]
i got the link on 'Finetune BERT-Bahasa'
i am trying to run text analysis using Bert. Please help to look at your bert-bahasa.
Thank you!

![image](https://user-images.githubusercontent.com/59812242/173771560-c36d5984-5f94-4cc9-ba4f-a09dd748d4fc.png)

**Comment by huseinzol05** [comment]
ops sorry, forgot to update the notebook, get it at https://github.com/huseinzol05/malaya/tree/master/pretrained-model/bert/tokenizer
