### ISSUE TITLE
malay-huggingface/bert-tiny-bahasa-cased last hidden shape 336

### ISSUE THREAD

**Issue by serenaroseaini** [huseinzol05/malaya#121]
Dear Encik Husein,

I used your pretrained Bert model, 'malay-huggingface/bert-tiny-bahasa-cased' from Hugging Face and run my dataset to extract text features. (Thank you for creating the model! :))
However, i got the last hidden layer shape 336 not the usual 768. If understood it corectly, 336 usually for Bert large model.
If i see your example in github, you got 768.
![image](https://user-images.githubusercontent.com/59812242/176826587-d7375ffa-12e4-4029-abe3-6871ffd21b80.png)

What i got;
![image](https://user-images.githubusercontent.com/59812242/176826770-595cac20-b7b4-4be2-bfde-da8a0b872757.png)

is there changes in the model config? do i need to change anything on the model to get 768-hidden?

**Comment by huseinzol05** [comment]
Tiny is 336, https://huggingface.co/malay-huggingface/bert-tiny-bahasa-cased/blob/main/TINY_config.json

Base is 768, https://huggingface.co/malay-huggingface/bert-base-bahasa-cased/blob/main/BASE_config.json

**Comment by serenaroseaini** [comment]
Ops, just notice what i pasted above is BASE_config.
Thank you for your clarification and information! :)
