### ISSUE TITLE
Semantic similarity model issue

### ISSUE THREAD

**Issue by zakaria47fs** [huseinzol05/malaya#122]
Using malaya: 4.8.0
It seems the semantic similarity function gives random similarity scores when comparing malay sentences,

Following short colab code you can try, when you keep running the "predict_proba" method between same sentences, you get each time a different similarity score,

https://colab.research.google.com/drive/10WgP-ftPGHTk_1Tf3Y9L0Sai8oIUPOMn#scrollTo=vgTYWt3636Bf

![image](https://user-images.githubusercontent.com/55286921/177257563-eddfe8c6-d73a-4e64-a074-fcb71b22c317.png)
![image](https://user-images.githubusercontent.com/55286921/177258006-67e155c1-a59e-481c-8dfb-eeedfda8d4a3.png)

**Comment by huseinzol05** [comment]
https://github.com/huseinzol05/malaya/issues/86, https://github.com/huseinzol05/malaya/issues/87
