### ISSUE TITLE
language_detection' has no attribute 'substring_rules'

### ISSUE THREAD

**Issue by jfl99** [huseinzol05/malaya#123]
I was trying to use the language detection in my project and I get below error when import the model.
![image](https://user-images.githubusercontent.com/47549207/181875864-a1f6235a-7c70-4ba6-abb6-676b6b94df8a.png)

**Comment by huseinzol05** [comment]
What is your malaya version? `malaya.language_detection.substring_rules` not yet released in PYPI.

**Comment by huseinzol05** [comment]
Released in 4.9!
