### ISSUE TITLE
translator.translate() error

### ISSUE THREAD

**Issue by wfkhrrzi** [huseinzol05/malaya#130]
Hi, im trying to do some translations using the provided [translator](https://github.com/huseinzol05/malaya/tree/master/misc/translator) but got this error 

![image](https://user-images.githubusercontent.com/66310901/186893125-3ad4de6b-13ba-42df-8a83-bc036aa8cc3d.png)

**Comment by huseinzol05** [comment]
The code is no longer able to use. I use this one currently, https://github.com/Songkeys/Translateer, really really good.

**Comment by wfkhrrzi** [comment]
alright will check on that. thank you boss!
