### ISSUE TITLE
Cannot import name '_tokenizer' from 'malaya.preprocessing'

### ISSUE THREAD

**Issue by wfkhrrzi** [huseinzol05/malaya#131]
Trying to do text augmentation then got this error
![image](https://user-images.githubusercontent.com/66310901/190344396-01fbfb10-a3a4-4dde-bf84-df38ec6cfda4.png)

**Comment by huseinzol05** [comment]
yup, its a bug, will fix it asap

**Comment by huseinzol05** [comment]
Fixed, install latest malaya from master branch,

```bash
pip3 uninstall malaya -y
pip3 install git+https://github.com/huseinzol05/malaya
```

**Comment by wfkhrrzi** [comment]
another error occurred. btw im using bert model
![image](https://user-images.githubusercontent.com/66310901/190386746-ffba66a7-2bfc-40f3-864d-42c04274308d.png)

**Comment by wfkhrrzi** [comment]
another error occurred. btw im using bert model
![image](https://user-images.githubusercontent.com/66310901/190389320-a30c845c-b42c-4a6f-a2be-771b4656ddd4.png)

**Comment by huseinzol05** [comment]
Fixed, install latest malaya from master branch,

```
pip3 uninstall malaya -y
pip3 install git+https://github.com/huseinzol05/malaya
```

**Comment by wfkhrrzi** [comment]
it's fixed thank you!
