### ISSUE TITLE
Spelling Correction Error

### ISSUE THREAD

**Issue by sw33tyin4** [huseinzol05/malaya#132]
![spellcorrectionmalaya](https://user-images.githubusercontent.com/97866325/192918102-c55a9672-6039-4996-a922-6454d67208fc.png)

I have install the required package but produced the following error. I also did try other types of spelling checker in malaya doc but still gave the same error.

**Comment by huseinzol05** [comment]
what is your malaya version?

**Comment by sw33tyin4** [comment]
> what is your malaya version?

Version: 4.7.1

**Comment by huseinzol05** [comment]
Need to bump to latest version

**Comment by sw33tyin4** [comment]
> Need to bump to latest version

may i know how do i get the latest version for malaya? thank you :)

**Comment by huseinzol05** [comment]
```
pip3 install malaya -U
```

**Comment by sw33tyin4** [comment]
> ```
> pip3 install malaya -U
> ```

Ok thank you.
