### ISSUE TITLE
topic modelling: lda2vec issue

### ISSUE THREAD

**Issue by DiyanaNadzirah** [huseinzol05/malaya#133]
hi, i encounter an issue while using the **lda2vec**  . I executed this function "lda2vec = malaya.topic_model.lda2vec(corp, vectorizer, n_topics = 20, switch_loss =1000, epoch = 5)" and the error says 'int' object has no attribute 'value'. 

**Version**

Tensorflow: 2.9.1
Malaya: 4.9.0

I`ll attach the screenshot of the error for your reference:
![image](https://user-images.githubusercontent.com/91946078/195249544-8ecd8d21-f7cc-4e34-9427-c5ba416f9d8c.png)

**Comment by huseinzol05** [comment]
Fixed in 5.0, https://malaya.readthedocs.io/en/5.0/load-topic-model-lda2vec.html, need to install malaya from 5.0 branch,

```bash
pip3 install git+https://github.com/huseinzol05/malaya@5.0
```
