### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 96: character maps to <undefined>

### ISSUE THREAD

**Issue by YuHengKit** [huseinzol05/malaya#134]
Hi, Im trying to use POS but faced this issue for this line of code:

`model = malaya.pos.transformer(model = 'albert')`

it should be decoding issue.

Thank you

**Comment by huseinzol05** [comment]
https://malaya.readthedocs.io/en/stable/running-on-windows.html
