### ISSUE TITLE
 AttributeError: module 'malaya' has no attribute 'knowledge_graph'

### ISSUE THREAD

**Issue by AqilLuqman** [huseinzol05/malaya#139]
Hello, I am a student in my second year and I am testing the ipynb file of knowledge graph from dependency. Am I using the wrong version of this file? I apologize in advance for asking about this error message.

**Comment by huseinzol05** [comment]
Yep, knowledge graph no longer in malaya 5.0, moved to https://malaya-graph.readthedocs.io/en/latest/,

```
pip install git+https://github.com/huseinzol05/malaya-graph.git
```
