### ISSUE TITLE
ValueError: perplexity must be less than n_samples

### ISSUE THREAD

**Issue by nazirulhafiz** [huseinzol05/malaya#148]
Hi Sir

I am download and trying the sentiment notebook at the link below

They work just fine. However, I ran into some error when to visualize sentence / word level in lower dimension. Please advice

![Issue Vectorize](https://github.com/huseinzol05/malaya/assets/94590075/70770f81-5382-40e6-9b52-898ec9daab7d)

[https://github.com/huseinzol05/malaya/blob/master/docs/load-sentiment.ipynb](url)

**Comment by huseinzol05** [comment]
sklearn versioning issue.
