### ISSUE TITLE
Cannot install malaya-graph

### ISSUE THREAD

**Issue by De4my** [huseinzol05/malaya#152]
Hi sorry for disturbing, but I have an issue where I cannot install one of the packages called malaya-graph. It said that no matching distribution was found.

Error:
![image](https://github.com/huseinzol05/malaya/assets/116957596/55619dbb-def1-4cf0-ac5f-2f87a2af3b57)

p/s: I already install malaya but it seems that the package is still not found
Hopefully I can use it because it was so cool to try out,Thanks

**Comment by huseinzol05** [comment]
I cannot found in the requirements, https://github.com/huseinzol05/malaya/blob/master/requirements.txt

**Comment by De4my** [comment]
> How do u installed it?

!pip install malaya 

then I try to install malaya_graph

**Comment by De4my** [comment]
> 

Maksudnya saya tersilap install malaya ke?

**Comment by De4my** [comment]
Alhamdulilah saya rasa saya dah dapat atasi masalah ini abang Husein

Solution:
1.!pip install malaya
2. import malaya.graph

**Comment by huseinzol05** [comment]
malaya-graph no longer maintain, saya masukkan ke dalam malaya, akan release gabungan tersebut dalam versi 5.1
