### ISSUE TITLE
Why is date is categorized as location?

### ISSUE THREAD

**Issue by tngflx** [huseinzol05/malaya#156]
![image](https://github.com/huseinzol05/malaya/assets/36429783/c96d7c91-8ad1-4483-a6e6-c97eda2c5313)
Hi, which model should I use to further increase the accuracy ya? seems like its even getting dates as location..

**Comment by huseinzol05** [comment]
you can try to stack, but i cannot confirm the accuracy. there is nothing much i can do, these models are deep learning based, the only way to improve the accuracy, added more dataset.

**Comment by tngflx** [comment]
can u teach me how to train on my own? im still pretty new to machine learning. perhaps i can specify whats the correct answer is and let the deep learning improve itself?
