### ISSUE TITLE
API access

### ISSUE THREAD

**Issue by hafizijainal** [huseinzol05/Malaya#24]
hai. can i access this project from outside? means the json available for me to use the function.

Thanks

**Comment by huseinzol05** [comment]
Erm, you need to install malaya inside your laptop after that call it.

**Comment by hafizijainal** [comment]
meanings i cannot just call it from my end?. i have web based and i want to call the POS tagging malay. is it possible without install the full project of yours.

Thanks

**Comment by huseinzol05** [comment]
Nope, this is a library, you can install it, after that wrap with API endpoints like Flask, Fastapi frameworks

**Comment by hafizijainal** [comment]
alright. tq bos. really helpful
