### ISSUE TITLE
toxic model trainning dataset

### ISSUE THREAD

**Issue by JDZW2014** [huseinzol05/Malaya#30]
Hi:
I'd like to ask you the train dataset of tocic model is this "https://github.com/huseinzol05/Malaya-Dataset/tree/master/toxicity"?  How much data you use?
thank you!!!

**Comment by huseinzol05** [comment]
randomly picked 80% to train, 20% to test. Can check all training sessions from here, https://github.com/huseinzol05/Malaya/tree/master/session/toxic

you will see I use,
```
from sklearn.model_selection import train_test_split

train_test_split(test_size = 0.2)
```
