### ISSUE TITLE
Malaya translator bug in Translate_Concurrent

### ISSUE THREAD

**Issue by biranchi2018** [huseinzol05/Malaya#31]
Hi Husein,

I tried the Malaya translator.
The translate_batch results are not in the same order of the input list of strings.

Please find the below screenshots.

![Translate_Bug1](https://user-images.githubusercontent.com/191425/73065885-982df800-3edf-11ea-9d31-d89161b5d74f.png)
![Translate_Bug2](https://user-images.githubusercontent.com/191425/73065902-a1b76000-3edf-11ea-9abe-1777d343545f.png)

==================================================================

![Translate_Bug3](https://user-images.githubusercontent.com/191425/73065913-a7ad4100-3edf-11ea-804a-34ccacfdc6c8.png)
![Translate_Bug4](https://user-images.githubusercontent.com/191425/73065919-abd95e80-3edf-11ea-90a0-8308edbdb9f5.png)

**Comment by biranchi2018** [comment]
Created a fix for the issue. Please review my pull request.

**Comment by huseinzol05** [comment]
Merged.
