### ISSUE TITLE
ELECTRA

### ISSUE THREAD

**Issue by parmarsuraj99** [huseinzol05/Malaya#41]
Any plans for distilling a pretrained ELECTRA model?

**Comment by huseinzol05** [comment]
thanks for letting us know about ELECTRA, we are doing pretraining for ELECTRA Base, should be completed around 5 days (23/04/2020), stay tune to download the model.

**Comment by parmarsuraj99** [comment]
That's Great. I am training for Indian Languages. Although, a smaller one

**Comment by huseinzol05** [comment]
added in huggingface, https://huggingface.co/models?filter=malay
