### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 109: character maps to <undefined>

### ISSUE THREAD

**Issue by msyazwan** [huseinzol05/Malaya#42]
I got the UnicodeDecodeError error everytime I run:

`model = malaya.sentiment.transformer(model = 'bert', size = 'base')`

**Full error:**
WARNING:tensorflow:From C:\Users\SZWNPC\Anaconda3\envs\malaya\lib\site-packages\malaya\_utils\_utils.py:119: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

WARNING:tensorflow:From C:\Users\SZWNPC\Anaconda3\envs\malaya\lib\site-packages\malaya\_utils\_utils.py:120: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-7-711b3ed9a74b> in <module>
----> 1 model_bert = malaya.sentiment.transformer(model = 'bert', size = 'base')

~\Anaconda3\envs\malaya\lib\site-packages\herpetologist\__init__.py in check(*args, **kwargs)
     86             nested_check(v, p)
     87 
---> 88         return func(*args, **kwargs)
     89 
     90     return check

~\Anaconda3\envs\malaya\lib\site-packages\malaya\sentiment.py in transformer(model, size, validate)
     91         model = model,
     92         size = size,
---> 93         validate = validate,
     94     )

~\Anaconda3\envs\malaya\lib\site-packages\malaya\_utils\_softmax_class.py in transformer(path, s3_path, class_name, label, model, size, validate)
     94 
     95         tokenizer, cls, sep = sentencepiece_tokenizer_bert(
---> 96             path[model][size]['tokenizer'], path[model][size]['vocab']
     97         )
     98 

~\Anaconda3\envs\malaya\lib\site-packages\malaya\_utils\_utils.py in sentencepiece_tokenizer_bert(path_tokenizer, path_vocab)
     74 
     75     with open(path_vocab) as fopen:
---> 76         v = fopen.read().split('\n')[:-1]
     77     v = [i.split('\t') for i in v]
     78     v = {i[0]: i[1] for i in v}

~\Anaconda3\envs\malaya\lib\encodings\cp1252.py in decode(self, input, final)
     21 class IncrementalDecoder(codecs.IncrementalDecoder):
     22     def decode(self, input, final=False):
---> 23         return codecs.charmap_decode(input,self.errors,decoding_table)[0]
     24 
     25 class StreamWriter(Codec,codecs.StreamWriter):

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 109: character maps to <undefined>

**Comment by huseinzol05** [comment]
Windows issue, check this one, https://github.com/huseinzol05/Malaya/issues/25
