### ISSUE TITLE
Word vector calculator num_closest bug

### ISSUE THREAD

**Issue by devennn** [huseinzol05/Malaya#45]
Hi,

I tried the wordvector. When using calculator, it throws TypeError for num_closest even though I'm passing an integer. The source code comment specifies int as default type, but not the args.

![bug1](https://user-images.githubusercontent.com/49480914/82452503-adfca400-9af2-11ea-8db0-c7a2afae3a1d.PNG)

**Comment by huseinzol05** [comment]
Thanks for submitting, I will bump it, will close this issue after pushed.

**Comment by huseinzol05** [comment]
Fixed, pip install malaya -U
