### ISSUE TITLE
Import error with update 3.6.2

### ISSUE THREAD

**Issue by kc980602** [huseinzol05/Malaya#46]
I have the following error with version 3.6.2

When I run 
`import malaya`
`ModuleNotFoundError: No module named 'malaya.text.keyword'`

I have testing with 3.6.0, this issue didn't occur.

**Comment by huseinzol05** [comment]
I added new module in 3.6.2, this should be quick to solve, will bump version.

**Comment by huseinzol05** [comment]
tested, bumped to 3.6.3, thanks!
