### ISSUE TITLE
I encountered this Error when executing preprocessing = malaya.preprocessing.preprocessing() for the first time in a new env. 

### ISSUE THREAD

**Issue by AishaYusuf** [huseinzol05/Malaya#48]
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-6-2e1f2ef0cdbf> in <module>
----> 1 preprocessing = malaya.preprocessing.preprocessing()

~\Anaconda3\envs\malaya20\lib\site-packages\malaya\preprocessing.py in preprocessing(normalize, annotate, lowercase, fix_unidecode, expand_hashtags, expand_english_contractions, translate_english_to_bm, remove_postfix, maxlen_segmenter, speller, **kwargs)
    612         maxlen_segmenter = maxlen_segmenter,
    613         translator = translator,
--> 614         speller = speller,
    615     )
    616 

~\Anaconda3\envs\malaya20\lib\site-packages\malaya\preprocessing.py in __init__(self, normalize, annotate, lowercase, fix_unidecode, expand_hashtags, expand_english_contractions, remove_postfix, maxlen_segmenter, translator, speller)
    355         self._tokenizer = SocialTokenizer(lowercase = lowercase).tokenize
    356         if self._expand_hashtags:
--> 357             self._segmenter = _Segmenter(maxlen_segmenter)
    358         self._expand_contractions = expand_english_contractions
    359         self._all_caps_tag = 'wrap'

~\Anaconda3\envs\malaya20\lib\site-packages\malaya\preprocessing.py in __init__(self, max_split_length)
    264     def __init__(self, max_split_length = 20):
    265         self.unigrams = _read_stats(1)
--> 266         self.bigrams = _read_stats(2)
    267         self.N = sum(self.unigrams.values())
    268         self.L = max_split_length

~\Anaconda3\envs\malaya20\lib\site-packages\malaya\preprocessing.py in _read_stats(gram)
    236 def _read_stats(gram = 1):
    237     with open(PATH_PREPROCESSING[gram]['model']) as fopen:
--> 238         return json.load(fopen)
    239 
    240 

~\Anaconda3\envs\malaya20\lib\json\__init__.py in load(fp, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    294         cls=cls, object_hook=object_hook,
    295         parse_float=parse_float, parse_int=parse_int,
--> 296         parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
    297 
    298 

~\Anaconda3\envs\malaya20\lib\json\__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    346             parse_int is None and parse_float is None and
    347             parse_constant is None and object_pairs_hook is None and not kw):
--> 348         return _default_decoder.decode(s)
    349     if cls is None:
    350         cls = JSONDecoder

~\Anaconda3\envs\malaya20\lib\json\decoder.py in decode(self, s, _w)
    335 
    336         """
--> 337         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338         end = _w(s, end).end()
    339         if end != len(s):

~\Anaconda3\envs\malaya20\lib\json\decoder.py in raw_decode(self, s, idx)
    351         """
    352         try:
--> 353             obj, end = self.scan_once(s, idx)
    354         except StopIteration as err:
    355             raise JSONDecodeError("Expecting value", s, err.value) from None

JSONDecodeError: Unterminated string starting at: line 1 column 91253438 (char 91253437)

**Comment by huseinzol05** [comment]
Seems like you disturb caching processing, try,

```python
import malaya
malaya.clear_cache('preprocessing')
```

After that, rerun,

```python
malaya.preprocessing.preprocessing()
```

I should put a suggestion what to do if got this error, will add the suggestion in next release.

**Comment by AishaYusuf** [comment]
Thanks Husein. It works like a charm. I wonder what i did to cause that disruption.
