### ISSUE TITLE
POS (Part-of-Speech Recognition) Model fails on certain sentences.

### ISSUE THREAD

**Issue by joshcx** [huseinzol05/Malaya#53]
POS model (albert) produces an error for years with the format 201X and 200X, e.g. 2008, 2009, 2010, 2011, 2012...2019 with a comma right after.
E.g. "Tahun ini 2015, saya sudah besar."

![Screenshot 2020-08-25 at 9 58 26 PM](https://user-images.githubusercontent.com/6434338/91183497-212f3b00-e71e-11ea-93a5-56aec52e3bdf.png)

![Screenshot 2020-08-25 at 10 28 26 PM](https://user-images.githubusercontent.com/6434338/91187230-85ec9480-e722-11ea-8d53-aba92bcaa4ef.png)

But sentences with other years are fine:
![Screenshot 2020-08-25 at 10 31 12 PM](https://user-images.githubusercontent.com/6434338/91187576-e5e33b00-e722-11ea-9658-e29da45f6bda.png)

And sentences which end (with a fullstop) with the year 201X. E.g. "Tahun ini 2015." are fine.

![Screenshot 2020-08-25 at 9 59 17 PM](https://user-images.githubusercontent.com/6434338/91183969-aca8cc00-e71e-11ea-9b47-545644a4a309.png)

![Screenshot 2020-08-25 at 10 03 17 PM](https://user-images.githubusercontent.com/6434338/91184207-f1ccfe00-e71e-11ea-8ff0-b70ecfe04c15.png)
![Screenshot 2020-08-25 at 10 03 35 PM](https://user-images.githubusercontent.com/6434338/91184217-f42f5800-e71e-11ea-98f1-a4d58f423b28.png)

Expected behavior:
Model should produce POS tags without issues, even for sentences with numbers.

Package versions:
1. malaya==3.8.1 (CPU version)
2. tensorflow==1.15.3
3. python==3.7.3

**Comment by huseinzol05** [comment]
Got it, this is totally a bug. thanks!

**Comment by huseinzol05** [comment]
Actually the bug comes from original https://github.com/google-research/albert/blob/master/tokenization.py

**Comment by huseinzol05** [comment]
Fixed, bumped to 3.8.2, reinstall latest version.
