### ISSUE TITLE
Normalizer groupby bug

### ISSUE THREAD

**Issue by khursani8** [huseinzol05/Malaya#56]
Reproduce bug
- https://colab.research.google.com/drive/1uIVNNw1AeQShkWBTZHRDGKgBua2TyrTh?usp=sharing

Propose fix
- At https://github.com/huseinzol05/Malaya/blob/master/malaya/normalize.py#L177

from
```
string = ''.join(''.join(s)[:2] for _, s in itertools.groupby(string))
```
to
```
string = ''.join(''.join(s) for _, s in itertools.groupby(string))
```

**Comment by huseinzol05** [comment]
Nice,

```
''.join(''.join(s)[:2] for _, s in itertools.groupby(string))
```

To solve the elongated problem, I think we will skip `groupby` if a word is a number / website.

**Comment by khursani8** [comment]
Thanks 👍
