### ISSUE TITLE
Retrain transformer models

### ISSUE THREAD

**Issue by asyrafzlkln96** [huseinzol05/Malaya#58]
Hi Husein,
Just a question,

Is there any way to fine tune or retrain the BERT models / Transformer models
using different datasets using transfer learning method?

My goal is to retrain the models using my own sentiment data and fine-tune the existing models.

Thanks,
Regards.
Asyraf.

**Comment by huseinzol05** [comment]
You can download pretrained models at https://github.com/huseinzol05/Malaya/tree/master/pretrained-model/bert

Or you can use huggingface, https://huggingface.co/models?search=huseinzol05

**Comment by huseinzol05** [comment]
I will create a simple tutorial using Tensorflow Estimator how to finetune Malaya pretrained models, give me 2-3 days.

**Comment by huseinzol05** [comment]
https://malaya.readthedocs.io/en/latest/tf-estimator-bert.html, also added ALXLNET and XLNET. good luck!
