### ISSUE TITLE
Missing vocab.txt

### ISSUE THREAD

**Issue by laopisai** [huseinzol05/Malaya#59]
Hi, I find that vocab.txt is generally missing from your hugging face models hosted in their cdn

**Comment by huseinzol05** [comment]
which one? I tested pretty much all the models.

**Comment by laopisai** [comment]
huggingface/transformers#5475 

excerpt from the issue above:
'huseinzol05/bert-base-bahasa-cased': ('stat: path should be string, bytes, os.PathLike or integer, not NoneType',),
'huseinzol05/tiny-bert-bahasa-cased': ('stat: path should be string, bytes, os.PathLike or integer, not NoneType',),

I've personally only tested bert-base-bahasa-cased and I get the same error msg. Currently I manually fix this issue by [downloading it](https://github.com/huseinzol05/Malaya/blob/master/pretrained-model/bert/BERT.wordpiece) from your Malaya repo. 

btw, thanks for your effort and contribution.

**Comment by liuchenbaidu** [comment]
the problem of denpa92/bert-base-cantonese is not solved.
