### ISSUE TITLE
module 'malaya.lexicon' has no attribute 'sentiment'

### ISSUE THREAD

**Issue by iamkatelim** [huseinzol05/Malaya#62]
Hi, I tried to run the following lines:

`sentiment_lexicon = malaya.lexicon.sentiment`
`sentiment_lexicon.keys()`

and get error message as below:

`AttributeError: module 'malaya.lexicon' has no attribute 'sentiment'`

Please advice, thanks!

**Comment by huseinzol05** [comment]
Alright, will look into it, thanks!

**Comment by huseinzol05** [comment]
Bumped to 4.0.1,

```bash
pip install malaya -U
```

Reopen if still got the same problem.

**Comment by iamkatelim** [comment]
Solved! Thanks 💯
