### ISSUE TITLE
How longs it takes to train a model from scratch?

### ISSUE THREAD

**Issue by hadifar** [huseinzol05/Malaya#63]
Hi, 
thanks for releasing your code. I have a question, I would like to reproduce your experiment for another language. Would you please tell me how long it takes to train `T5` (large,  base) models?

**Comment by huseinzol05** [comment]
If you check tensorboard from https://github.com/huseinzol05/Malaya/tree/master/pretrained-model/t5#download, https://tensorboard.dev/experiment/v0ZAAd2cQjOGO6ETmA1IRQ/, took almost 7 days for T5 base using TPU V3-8.

**Comment by hadifar** [comment]
Thanks :)
