### ISSUE TITLE
module 'malaya.entity' has no attribute 'deep_model'

### ISSUE THREAD

**Issue by dicksonding** [huseinzol05/Malaya#64]
Hi, 

I experience problem module 'malaya.entity' has no attribute 'deep_model' from the following code:-

`bahdanau_entities = malaya.entity.deep_model('bahdanau')`

this code I was copy directly from [https://malaya.readthedocs.io/en/latest/load-clustering.html](url) 

I tried to search in this GitHub repository for "deep_model" however can't find anything useful lead to solve this problem.

**Comment by huseinzol05** [comment]
`bahdanau_entities = malaya.entity.deep_model('bahdanau')` already deprecated. Use any transformer model from https://malaya.readthedocs.io/en/latest/load-entities.html. I forgot to update that documentation. Will do it

**Comment by huseinzol05** [comment]
Update docs, https://malaya.readthedocs.io/en/latest/load-clustering.html#Cluster-same-word-structure-based-on-POS-and-Entities
