### ISSUE TITLE
Segmentation Improvement 

### ISSUE THREAD

**Issue by iamkatelim** [huseinzol05/Malaya#65]
Hi, I noticed that there were some improvements on segmentation. For example:

`risau -> r is au`
`budak -> bu dak`
`cerita -> cer i ta`

and there were many more. 
I did tried to cleared session after go through documentations but doesn't help much.
Thank you. 👍🏽

**Comment by huseinzol05** [comment]
thanks for reminding me that! We are going to release better segmentation model using Transformer!

**Comment by iamkatelim** [comment]
Thanks Husein! Looking forward to it 👍🏽

**Comment by huseinzol05** [comment]
https://malaya.readthedocs.io/en/latest/load-segmentation.html

Install latest version.
