### ISSUE TITLE
confuse init_checkpoint in T5-base operative_config.gin

### ISSUE THREAD

**Issue by justinphan3110** [huseinzol05/Malaya#66]
Hi in your pretrained_models_base_operative_config.gin of pre-train T5 model there was a line 
''' init_checkpoint = "gs://mesolitica-general/t5-base/model.ckpt-100000 '''
was this the checkpoint for the Malaya version of T5 or the checkpoint for the original T5 from model. And does this affect the pretrain process at all ?

**Comment by huseinzol05** [comment]
checkpoint for Malaya version, feel free to download pretrained model from https://github.com/huseinzol05/Malaya/tree/master/pretrained-model/t5#download and upload to your own GCS. You need to store the checkpoint inside GCS if want to use TPU.

**Comment by justinphan3110** [comment]
got it thanks
