### ISSUE TITLE
Regarding sentiment analysis function

### ISSUE THREAD

**Issue by ikerepeks** [huseinzol05/Malaya#72]
I have an issue regarding the usage of sentiment analysis predict. I followed the same example as in documentation but i gt this error. Last time on Dec 8th I didn't encounter this error.

``` 
TypeError                                 Traceback (most recent call last)
<ipython-input-13-ebda4f58f0be> in <module>()
      1 model = malaya.sentiment.multinomial()
----> 2 model.predict([string1, string2])

7 frames
/usr/local/lib/python3.6/dist-packages/herpetologist/__init__.py in check(*args, **kwargs)
     98                 nested_check(v, p)
     99 
--> 100         return func(*args, **kwargs)
    101 
    102     return check

TypeError: naive() takes 0 positional arguments but 1 was given 
``` 
Im quite new to python, so the problem maybe on my side but i still can't grasp on how to fix it. Im using Google Colab as the IDE

**Comment by ihsanramli** [comment]
Hi, I'm ha

> I have an issue regarding the usage of sentiment analysis predict. I followed the same example as in documentation but i gt this error. Last time on Dec 8th I didn't encounter this error.
> 
> ```
> TypeError                                 Traceback (most recent call last)
> <ipython-input-13-ebda4f58f0be> in <module>()
>       1 model = malaya.sentiment.multinomial()
> ----> 2 model.predict([string1, string2])
> 
> 7 frames
> /usr/local/lib/python3.6/dist-packages/herpetologist/__init__.py in check(*args, **kwargs)
>      98                 nested_check(v, p)
>      99 
> --> 100         return func(*args, **kwargs)
>     101 
>     102     return check
> 
> TypeError: naive() takes 0 positional arguments but 1 was given 
> ```
> 
> Im quite new to python, so the problem maybe on my side but i still can't grasp on how to fix it. Im using Google Colab as the IDE

Hi, I'm having this issue too. Have you found the solutions?

**Comment by ihsanramli** [comment]
@ikerepeks 

Hi, I think the latest version has some issues with **`stem.py`** methods.

Need to revert to previous version first.

```
pip uninstall malaya
pip install malaya==4.0
```

**Comment by ikerepeks** [comment]
I see, guess i'll just use the previous version for now.. Thank you

**Comment by huseinzol05** [comment]
Oh, ya, i found the bug, I introduced it when I did some housekeeping, will fix it asap!

**Comment by huseinzol05** [comment]
bumped to 4.0.9.1, tested on emotion, sentiment and toxicity.

**Comment by huseinzol05** [comment]
feel free to reopen if got the same issue.
