### ISSUE TITLE
AttributeError 

### ISSUE THREAD

**Issue by syukri97** [huseinzol05/malaya#74]
Assalam and hi,
I just try to write code from the malaya documentation prepared for segmentation

Model = malaya.segmentation.transformer(model = 'small') 
But its appear the error :
AttributeError: module 'malaya' has no attribute 'segmentation' 
The error also occur for verterbi algorithm

Thanks alot for your response

**Comment by huseinzol05** [comment]
Tested with latest version, make sure you installed latest version,

```python
import malaya
malaya.__version__
-> '4.1.0.0'

malaya.segmentation.transformer
-> <function transformer at 0x7f4e779fcf28>
```

**Comment by syukri97** [comment]
Ok thanks, problem solved
