### ISSUE TITLE
ModuleNotFoundError: No module named 'transformer'

### ISSUE THREAD

**Issue by faizmisman** [huseinzol05/malaya#75]
Hi. I tried running bert-pytorch-to-tf1.ipynb and this error occurred.

--------------------------------------------------------------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-bca87b6f049e> in <module>
      1 import tensorflow as tf
      2 import torch
----> 3 from transformer.modeling import TinyBertForPreTraining, BertForMaskedLM, TinyBertForPreTraining
      4 import bert.modeling, bert.tokenization

ModuleNotFoundError: No module named 'transformer'
---------------------------------------------------------------------------------------------------------------------------------

I'm using Malaya==4.0.9.1, pytorch==1.7.1 and transformers==3.3.1

**Comment by huseinzol05** [comment]
I think I forgot to add a note in there, need to run in https://github.com/huawei-noah/Pretrained-Language-Model/tree/master/TinyBERT
