### ISSUE TITLE
UnicodeDecodeError for Windows

### ISSUE THREAD

**Issue by joshcx** [huseinzol05/malaya#76]
Hello,

I get this error when trying to run on Windows. Mac and Linux works fine.

malaya.zero_shot.classification.transformer(model="alxlnet")

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 117: character maps to <undefined>

If you just change the line:
```
site-packages\malaya\text\bpe.py", line 498, in sentencepiece_tokenizer_bert
   with open(path_vocab) as fopen:
        v = fopen.read().split('\n')[:-1]
```

to 

```
with open(path_vocab, encoding='UTF-8') as fopen:
        v = fopen.read().split('\n')[:-1]
```

It should fix the issue for windows users without having to change Windows system language locale like in #25

**Comment by huseinzol05** [comment]
It is better to change the encoding using OS setting.
