### ISSUE TITLE
Error running zero shot model on Windows

### ISSUE THREAD

**Issue by joshcx** [huseinzol05/malaya#77]
Hello,

I get the following error message when trying to run:

`malaya.zero_shot.classification.transformer(model="alxlnet")`

This is the error message:

```
File "lib\site-packages\malaya\supervised\softmax.py", line 72, in transformer
    g = load_graph(path['model'], **kwargs)
\malaya\function\__init__.py", line 115, in load_graph
    
graph_def.ParseFromString(f.read())

google.protobuf.message.DecodeError: Error parsing message
```

Python 3.7.5
Malaya 4.2.0
OS: Windows 10

**Comment by huseinzol05** [comment]
Did you tried to change encoding for Windows?
