### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by syukri97** [huseinzol05/malaya#80]
Hi. 
I have a issues when try to load custom word vector on malaya.

When i run this code:
word_vector_news = malaya.wordvector.load(embedded_news, vocab_news)
word_vector_wiki = malaya.wordvector.load(embedded_wiki, vocab_wiki)

there's error like this:
TypeError                                 Traceback (most recent call last)
<ipython-input-28-cf4c4c9ff235> in <module>
----> 1 word_vector_news = malaya.wordvector.load(embedded_news, vocab_news)
      2 word_vector_wiki = malaya.wordvector.load(embedded_wiki, vocab_wiki)

c:\users\goku\appdata\local\programs\python\python37\lib\site-packages\herpetologist\__init__.py in check(*args, **kwargs)
     93 
     94             for v, p in zip(args, parameters):
---> 95                 nested_check(v, p)
     96 
     97             for p, v in kwargs.items():

c:\users\goku\appdata\local\programs\python\python37\lib\site-packages\herpetologist\__init__.py in nested_check(v, p)
     86                     raise TypeError(
     87                         proper_text(
---> 88                             f'type of argument "{p}" from {function} must be {t}'
     89                         )
     90                     )

TypeError: type of argument "dictionary" from load(embed_matrix, dictionary) must be 'dict'

Can i know why? and what is the solution? Thanks a lot for any response

**Comment by huseinzol05** [comment]
I follow https://malaya.readthedocs.io/en/latest/load-wordvector.html,

```python
import malaya
vocab_news, embedded_news = malaya.wordvector.load_news()
word_vector_news = malaya.wordvector.load(embedded_news, vocab_news)
```
