### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '²' in normalizer

### ISSUE THREAD

**Issue by xiohannnnn** [huseinzol05/malaya#81]
Hi there, 

This is my code:
data['new_column'] = np.vectorize(normalizer.normalize)(data['tweet2'], normalize_entity = False)

Can i know why / how to solve the issue for
invalid literal for int() with base 10: '²'?

Thanks! :)

**Comment by huseinzol05** [comment]
Cannot do this `np.vectorize(normalizer.normalize)(data['tweet2'], normalize_entity = False)`.

**Comment by xiohannnnn** [comment]
Hi @huseinzol05 ,

If cannot do vectorize, could you please suggest how can I normalize the tweets data in dataframe?
