### ISSUE TITLE
Thread safe of Malaya

### ISSUE THREAD

**Issue by dicksonding** [huseinzol05/malaya#83]
Hi,

Currently I am planing to use Malaya in server environment, where there will be multiple request(s) from user's browser thus would require Malaya to be able to process in multi-threads. 

I would like to know whether Malaya has this capability? I am aware that Tensorflow can run multi-threads so would like to double confirm whether Malaya can do the same.

Thanks.

Regards,
Ding

**Comment by huseinzol05** [comment]
Check https://github.com/huseinzol05/malaya/tree/master/misc/deployment, https://malaya.readthedocs.io/en/latest/load-deployment.html
Also support multigpus, https://malaya.readthedocs.io/en/latest/gpu-environment.html
