### ISSUE TITLE
Sentiment analysis output is non deterministic

### ISSUE THREAD

**Issue by patrickxchong** [huseinzol05/malaya#86]
Hello, I was following the sentiment analysis documentation at https://malaya.readthedocs.io/en/latest/load-sentiment.html#Load-Transformer-model
, but found out that the results of the BERT model are non deterministic for string2 (results of predict_proba for all strings change on each run as well). I tried setting a random seed with tensorflow but that didn't change anything. Is there anything that I'm missing to get deterministic results?

Below are the strings (from the documentation) and also screenshot of the results. 

```
string1 = 'Sis, students from overseas were brought back because they are not in their countries which is if something happens to them, its not the other countries’ responsibility. Student dalam malaysia ni dah dlm tggjawab kerajaan. Mana part yg tak faham?'
string2 = 'Harap kerajaan tak bukak serentak. Slowly release week by week. Focus on economy related industries dulu'
string3 = 'Idk if aku salah baca ke apa. Bayaran rm350 utk golongan umur 21 ke bawah shj ? Anyone? If 21 ke atas ok lah. If umur 21 ke bawah?  Are you serious? Siapa yg lebih byk komitmen? Aku hrp aku salah baca. Aku tk jumpa artikel tu'
string4 = 'Jabatan Penjara Malaysia diperuntukkan RM20 juta laksana program pembangunan Insan kepada banduan. Majikan yang menggaji bekas banduan, bekas penagih dadah diberi potongan cukai tambahan sehingga 2025.'
```

![image](https://user-images.githubusercontent.com/20418855/118619957-a223ea80-b7f7-11eb-98c3-db031563d3ac.png)

Possibly related issue: https://github.com/google-research/bert/issues/583

**Comment by huseinzol05** [comment]
Here I compared BERT and ALBERT,

```python
import tensorflow as tf
import malaya
tf.compat.v1.set_random_seed(1234)

model = malaya.sentiment.transformer(model = 'bert')
albert = malaya.sentiment.transformer(model = 'albert')

string4 = 'Jabatan Penjara Malaysia diperuntukkan RM20 juta laksana program pembangunan Insan kepada banduan. Majikan yang menggaji bekas banduan, bekas penagih dadah diberi potongan cukai tambahan sehingga 2025.'
```

Below is for BERT,

```python
# make sure no dropout operation
for node in model._sess.graph_def.node:
    op = node.op.lower()
    if 'drop' in op:
        print(node.name, node.op)

model.predict_proba([string4])
model.predict_proba([string4])
model.predict_proba([string4])
model.predict_proba([string4])
model.predict_proba([string4])
```

<img width="1096" alt="Screenshot 2021-05-20 at 2 23 38 PM" src="https://user-images.githubusercontent.com/19810909/118929368-015c3900-b977-11eb-9059-0bd7e2149734.png">

Below is for ALBERT,

```python
# make sure no dropout operation
for node in albert._sess.graph_def.node:
    op = node.op.lower()
    if 'drop' in op:
        print(node.name, node.op)

albert.predict_proba([string4])
albert.predict_proba([string4])
albert.predict_proba([string4])
albert.predict_proba([string4])
albert.predict_proba([string4])
```

<img width="772" alt="Screenshot 2021-05-20 at 2 24 38 PM" src="https://user-images.githubusercontent.com/19810909/118929457-22248e80-b977-11eb-86c3-ecfa1a3352b5.png">

**Comment by patrickxchong** [comment]
Yeah I compared all the available models and the output is deterministic for albert and tiny-albert, but non-deterministic for bert, tiny-bert, xlnet and axlnet. So I guess the question is, is the non-deterministic nature a feature, or is it a bug?

**Comment by huseinzol05** [comment]
nature for deep learning models.

**Comment by huseinzol05** [comment]
Might want to read https://github.com/tensorflow/tensorflow/issues/3103.
