### ISSUE TITLE
dependency parser tags

### ISSUE THREAD

**Issue by waterhall** [huseinzol05/malaya#88]
Hello, the description from malaya.dependency.describe() shows 26 different dependency tags, but when I go to 
`INFO:root:you can read more from https://universaldependencies.org/treebanks/id_pud/index.html`
there are a lot more dependency relations: 
acl – acl:relcl – advcl – advmod – advmod:emph – amod – appos – aux – case – case:adv – cc – cc:preconj – ccomp – compound – compound:a – conj – cop – csubj – csubj:pass – det – discourse – dislocated – fixed – flat – flat:foreign – flat:name – goeswith – iobj – mark – nmod – nmod:lmod – nmod:poss – nmod:tmod – nsubj – nsubj:pass – nummod – obj – obl – obl:agent – obl:tmod – orphan – parataxis – punct – root – vocative – xcomp

Then when I look at the source code in dependency.py, it shows these tags (i put them in a list):
`['PAD', 'X', 'nsubj','cop','det','root','nsubj:pass','acl','case','obl','flat','punct',
                    'appos','amod','compound','advmod','cc','obj','conj','mark','advcl','nmod','nummod',
                    'dep','xcomp','ccomp','parataxis','compound:plur','fixed','aux','csubj','iobj','csubj:pass']` 

All 3 tag sets don't match.
May I know what treebank the dependency parser was trained on? 

Is it https://github.com/UniversalDependencies/UD_Indonesian-GSD/tree/master? Because that fits most closely to the tags shown in dependency.py, except for the addition of compound:plur, PAD, and X.

An explanation would be very helpful (also what is compound:plur, PAD and X). Also sometimes the parser returns more than 1 root tag, is that intended? thanks!

**Comment by huseinzol05** [comment]
I think they updated the tags.
