### ISSUE TITLE
BigBird pretrained model

### ISSUE THREAD

**Issue by matthewtnx** [huseinzol05/malaya#92]
Hi, I am unable to find the download link for the pretrained model for bigbird. Does anyone know where it is?

Thank you.

**Comment by huseinzol05** [comment]
You do not need to pretrain BigBird model.
BigBird just an extension for existing Bert / Pegasus model.
If you want to finetune BigBird for classification / span tasks, just download any pretrained bert models and finetune it.
If you want to do seq2seq tasks, download pretrained Pegasus and finetune it.

**Comment by matthewtnx** [comment]
Hi @huseinzol05 , thank you for the reply. I would like to find out if there is any way to download the BigBird model from the long text translation example so that I would be able to use it even without internet access. Or would I have to download Pegasus and finetune it so that I would have the model on my machine?
Thank you.
