### ISSUE TITLE
TTS Models cache error

### ISSUE THREAD

**Issue by AfifFaizJusoh** [huseinzol05/malaya#94]
I am trying to run the TTS models specifically the fastspeech2 model but this error always come even if I have already delete_cache. Please help.

downloading frozen model to C:\Users\faiz6\Malaya/tts/fastspeech2-haqkiem/model.pb
1.00MB [00:00, 501MB/s]                    
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
d:\OneDrive\HOOP-WFH\malay_ai_chatbot\mychatbot\lib\site-packages\google\protobuf\internal\python_message.py in MergeFromString(self, serialized)
   1138     try:
-> 1139       if self._InternalParse(serialized, 0, length) != length:
   1140         # The only reason _InternalParse would return early is if it

d:\OneDrive\HOOP-WFH\malay_ai_chatbot\mychatbot\lib\site-packages\google\protobuf\internal\python_message.py in InternalParse(self, buffer, pos, end)
   1191         old_pos = new_pos
-> 1192         (data, new_pos) = decoder._DecodeUnknownField(
   1193             buffer, new_pos, wire_type)  # pylint: disable=protected-access

d:\OneDrive\HOOP-WFH\malay_ai_chatbot\mychatbot\lib\site-packages\google\protobuf\internal\decoder.py in _DecodeUnknownField(buffer, pos, wire_type)
    988   elif wire_type == wire_format.WIRETYPE_START_GROUP:
--> 989     (data, pos) = _DecodeUnknownFieldSet(buffer, pos)
    990   elif wire_type == wire_format.WIRETYPE_END_GROUP:

d:\OneDrive\HOOP-WFH\malay_ai_chatbot\mychatbot\lib\site-packages\google\protobuf\internal\decoder.py in _DecodeUnknownFieldSet(buffer, pos, end_pos)
    962   while end_pos is None or pos < end_pos:
--> 963     (tag_bytes, pos) = ReadTag(buffer, pos)
    964     (tag, _) = _DecodeVarint(tag_bytes, 0)

d:\OneDrive\HOOP-WFH\malay_ai_chatbot\mychatbot\lib\site-packages\google\protobuf\internal\decoder.py in ReadTag(buffer, pos)
    191   start = pos
--> 192   while six.indexbytes(buffer, pos) & 0x80:
    193     pos += 1

IndexError: index out of bounds on dimension 1

During handling of the above exception, another exception occurred:

DecodeError                               Traceback (most recent call last)
d:\OneDrive\HOOP-WFH\malay_ai_chatbot\mychatbot\lib\site-packages\malaya_boilerplate\frozen_graph.py in load_graph(frozen_graph_filename, **kwargs)
    259             graph_def = tf.compat.v1.GraphDef()
--> 260             graph_def.ParseFromString(f.read())
    261         except Exception as e:

d:\OneDrive\HOOP-WFH\malay_ai_chatbot\mychatbot\lib\site-packages\google\protobuf\message.py in ParseFromString(self, serialized)
    198     self.Clear()
--> 199     return self.MergeFromString(serialized)
    200 

d:\OneDrive\HOOP-WFH\malay_ai_chatbot\mychatbot\lib\site-packages\google\protobuf\internal\python_message.py in MergeFromString(self, serialized)
   1144       # Now ord(buf[p:p+1]) == ord('') gets TypeError.
-> 1145       raise message_mod.DecodeError('Truncated message.')
   1146     except struct.error as e:

DecodeError: Truncated message.

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
d:\OneDrive\HOOP-WFH\malay_ai_chatbot\TTS_malay.py in 
----> 21 haqkiem = malaya_speech.tts.fastspeech2(model='haqkiem')

d:\OneDrive\HOOP-WFH\malay_ai_chatbot\mychatbot\lib\site-packages\malaya_speech\tts.py in fastspeech2(model, quantized, pad_to, true_case, **kwargs)
    378         **kwargs
    379     )
--> 380     return tts.fastspeech_load(
    381         path = PATH_TTS_FASTSPEECH2,
    382         s3_path = S3_PATH_TTS_FASTSPEECH2,

d:\OneDrive\HOOP-WFH\malay_ai_chatbot\mychatbot\lib\site-packages\malaya_speech\supervised\tts.py in fastspeech_load(path, s3_path, model, name, normalizer, quantized, **kwargs)
     45         model_path = 'model'
     46 
---> 47     g = load_graph(path[model][model_path], **kwargs)
     48     inputs = ['Placeholder', 'speed_ratios', 'f0_ratios', 'energy_ratios']
     49     outputs = ['decoder_output', 'post_mel_outputs']

d:\OneDrive\HOOP-WFH\malay_ai_chatbot\mychatbot\lib\site-packages\malaya_boilerplate\frozen_graph.py in load_graph(frozen_graph_filename, **kwargs)
    260             graph_def.ParseFromString(f.read())
    261         except Exception as e:
--> 262             raise Exception(
    263                 f"{e}, file corrupted due to some reasons, please run `{__package__}.utils.delete_cache('{path}')` and try again"
    264             )

Exception: Truncated message., file corrupted due to some reasons, please run `malaya.utils.delete_cache('tts\fastspeech2-haqkiem')` and try again

**Comment by huseinzol05** [comment]
Wrong repository.
