### ISSUE TITLE
import malaya issue

### ISSUE THREAD

**Issue by Adlifuddin** [huseinzol05/malaya#97]
I think there's an issue when importing malaya. The issue arises in file pagerank.py line 3 from networkx import nx. I've tried to clone and change that line to import networkx as nx and manually install from the source. The issue has been resolve.

**Comment by huseinzol05** [comment]
Cannot replicate, https://colab.research.google.com/drive/1HtLmcU3etpEKQFccBuGoHOYv5NSbgWtr?usp=sharing, should be not a problem

**Comment by huseinzol05** [comment]
```
from networkx import nx
nx
```
<module 'networkx' from '/usr/local/lib/python3.7/dist-packages/networkx/__init__.py'>

```
import networkx as nx
nx
```
<module 'networkx' from '/usr/local/lib/python3.7/dist-packages/networkx/__init__.py'>
