### ISSUE TITLE
How to get '*tatabahasa-*.pkl'?

### ISSUE THREAD

**Issue by cingtiye** [huseinzol05/malaya#99]
I'm very happy that malaya can achieve all of  'seq2edits' from the paper "Seq2Edits: Sequence Transduction Using Span-level Edit Operations". When I pay attenon on the code from tatabahasa/prepare-tatabahasa.ipynb,

```python
files = glob('/home/husein/pure-text/*tatabahasa-*.pkl')
```
I found I lack of  a series of dataset about *tatabahasa-*.pkl.

Could you please tell me how to get '*tatabahasa-*.pkl'?

Thanks.

**Comment by huseinzol05** [comment]
You need to run kesalahan-tatabahasa-*.ipynb, each notebook generate one particular grammar mistake.

**Comment by cingtiye** [comment]
Thank you very much. And I'm sorry to ask you again that how can I get 'filtered-dumping-wiki.txt'?
Please.
Thans.
